### ISSUE TITLE
Persistence / MySQL should be disabled in Typo 3

### ISSUE THREAD

**Issue by motin** [kenjis/php-framework-benchmark#40]
Currently Typo 3 tries to connect to MySQL during the benchmark:

```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111)' in /public/typo3f-3.0/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Stack trace:
#0 /public/typo3f-3.0/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct()
#1 /public/typo3f-3.0/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(45): Doctrine\\DBAL\\Driver\\PDOConnection->__construct()
#2 /public/typo3f-3.0/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\\DBAL\\Driver\\PDOMySql\\Driver->connect()
#3 /public/typo3f-3.0/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Persistence_Doctrine_EntityManagerFactory.php(116): Doctrine\\DBAL\\Connection->connect()
#4 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php(454): TYPO3\\Flow\\Persistence\\Doctrine\\EntityManagerFactory_Original->create()
#5 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/ObjectManager.php(169): TYPO3\\Flow\\Object\\ObjectManager->buildObjectByFactory()
#6 /public/typo3f-3.0/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Persistence_Doctrine_PersistenceManager.php(669): TYPO3\\Flow\\Object\\ObjectManager->get()
#7 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/DependencyProxy.php(57): Closure$TYPO3\\Flow\\Persistence\\Doctrine\\PersistenceManager::Flow_Proxy_injectProperties
#2()
#8 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Object/DependencyInjection/DependencyProxy.php(94): TYPO3\\Flow\\Object\\DependencyInjection\\DependencyProxy->_activateDependency()
#9 /public/typo3f-3.0/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Persistence_Doctrine_PersistenceManager.php(58): TYPO3\\Flow\\Object\\DependencyInjection\\DependencyProxy->__call()
#10 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Scripts.php(480): TYPO3\\Flow\\Persistence\\Doctrine\\PersistenceManager_Original->initialize()
#11 (): TYPO3\\Flow\\Core\\Booting\\Scripts::initializePersistence()
#12 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Step.php(49): call_user_func()
#13 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(101): TYPO3\\Flow\\Core\\Booting\\Step->__invoke()
#14 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#15 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#16 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#17 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#18 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#19 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#20 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(105): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#21 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Booting/Sequence.php(85): TYPO3\\Flow\\Core\\Booting\\Sequence->invokeStep()
#22 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php(142): TYPO3\\Flow\\Core\\Booting\\Sequence->invoke()
#23 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Http/RequestHandler.php(100): TYPO3\\Flow\\Http\\RequestHandler->boot()
#24 /public/typo3f-3.0/Packages/Framework/TYPO3.Flow/Classes/TYPO3/Flow/Core/Bootstrap.php(112): TYPO3\\Flow\\Http\\RequestHandler->handleRequest()
#25 /public/typo3f-3.0/Web/index.php(31): TYPO3\\Flow\\Core\\Bootstrap->run()
#26 {main}
```

I tried to disable this via configuration but I must admit that I don't understand much of the Typo 3 documentation.

**Comment by kenjis** [comment]
I stoped mysqld on my VM. But the error does not occur.

**Comment by motin** [comment]
Just thinking that it may explain the notably bad benchmark results for typo3. If it is trying to connect to MySQL on every request in order to spell out a hard-coded "Hello World" it sure sounds inefficient :)
